
import "./globals.css";
import Header from "@/components/Header/header";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Noteapp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Header />
        <main>
        <Toaster position="top-right" />
        {children}
        </main>
      </body>
    </html>
  )
}
